name: Run Browser Tests

on:
  workflow_dispatch:
    inputs:
      users:
        description: Number of users
        required: true
        default: '20'
      iterations:
        description: Iterations per user
        required: true
        default: '50'
      messages:
        description: Messages (true or false)
        required: true
        default: 'false'
      emotes:
        description: Emotes (true or false)
        required: true
        default: 'false'
      concurrent:
        description: Concurrent users per job (Up to 5 works well)
        required: true
        default: '3'

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    name: Generate Matrix
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - id: gen-matrix
        env:
          concurrent: ${{ github.event.inputs.concurrent }}
          users: ${{ github.event.inputs.users }}
        run: |
          printf '::set-output name=matrix::%s' \
            "$(jq -ecn \
              --argjson users "$users" --argjson concurrent "$concurrent" \
              '{"offset": [range(0; $users / $concurrent) * $concurrent]}')"

  test:
    runs-on: ubuntu-latest
    name: "Offset #${{ matrix.offset }}"
    needs: gen-matrix
    strategy:
      matrix: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache frontend dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci --prefer-offline

      - name: Run Browser
        env:
          concurrent: ${{ github.event.inputs.concurrent }}
          emotes: ${{ github.event.inputs.emotes }}
          iterations: ${{ github.event.inputs.iterations }}
          messages: ${{ github.event.inputs.messages }}
          offset: ${{ matrix.offset }}
          url: ${{ secrets.LIVI_URL }}
        run: |
          if [ "$emotes" = 'true' ]; then
            flags="$flags --emotes"
          fi
          if [ "$messages" = 'true' ]; then
            flags="$flags --messages"
          fi
          npm run browser -- --url="$url" --limit="$concurrent" --offset="$offset" --iterations="$iterations" $flags --headless

      - name: Upload Error Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: error-screenshots-${{ matrix.offset }}
          path: ./errors/*
          if-no-files-found: ignore
