name: Run Tests

# on: workflow_dispatch
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Run Test #${{ matrix.offset }}'
    strategy:
      matrix:
        offset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache frontend dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci --prefer-offline

      - name: Run Browser
        env:
          offset: ${{ matrix.offset }}
        run: |
          npm run browser -- --limit=1 --offset=$offset --headless
